/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace com.boxalino.p13n.api.thrift
{
  /// <summary>
  /// Whether facets should be order by population descending or by collation
  /// </summary>
  public enum FacetSortOrder
  {
    POPULATION = 1,
    COLLATION = 2,
  }
}
