/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class AutocompleteResponseBundle : TBase
{
  private List<AutocompleteResponse> _responses;

  public List<AutocompleteResponse> Responses
  {
    get
    {
      return _responses;
    }
    set
    {
      __isset.responses = true;
      this._responses = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool responses;
  }

  public AutocompleteResponseBundle() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 11:
            if (field.Type == TType.List) {
              {
                Responses = new List<AutocompleteResponse>();
                TList _list174 = iprot.ReadListBegin();
                for( int _i175 = 0; _i175 < _list174.Count; ++_i175)
                {
                  AutocompleteResponse _elem176;
                  _elem176 = new AutocompleteResponse();
                  _elem176.Read(iprot);
                  Responses.Add(_elem176);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("AutocompleteResponseBundle");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Responses != null && __isset.responses) {
        field.Name = "responses";
        field.Type = TType.List;
        field.ID = 11;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Responses.Count));
          foreach (AutocompleteResponse _iter177 in Responses)
          {
            _iter177.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("AutocompleteResponseBundle(");
    bool __first = true;
    if (Responses != null && __isset.responses) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Responses: ");
      __sb.Append(Responses);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

