/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

/// <summary>
/// Whether facets should be order by population descending or by collation
/// </summary>
public enum FacetSortOrder
{
  POPULATION = 1,
  COLLATION = 2,
}
