/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class ProfilePropertyValue : TBase
{
  private string _profileId;
  private string _propertyName;
  private string _propertyValue;
  private int _confidence;

  public string ProfileId
  {
    get
    {
      return _profileId;
    }
    set
    {
      __isset.profileId = true;
      this._profileId = value;
    }
  }

  public string PropertyName
  {
    get
    {
      return _propertyName;
    }
    set
    {
      __isset.propertyName = true;
      this._propertyName = value;
    }
  }

  public string PropertyValue
  {
    get
    {
      return _propertyValue;
    }
    set
    {
      __isset.propertyValue = true;
      this._propertyValue = value;
    }
  }

  public int Confidence
  {
    get
    {
      return _confidence;
    }
    set
    {
      __isset.confidence = true;
      this._confidence = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool profileId;
    public bool propertyName;
    public bool propertyValue;
    public bool confidence;
  }

  public ProfilePropertyValue() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              ProfileId = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              PropertyName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              PropertyValue = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              Confidence = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("ProfilePropertyValue");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ProfileId != null && __isset.profileId) {
        field.Name = "profileId";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ProfileId);
        oprot.WriteFieldEnd();
      }
      if (PropertyName != null && __isset.propertyName) {
        field.Name = "propertyName";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(PropertyName);
        oprot.WriteFieldEnd();
      }
      if (PropertyValue != null && __isset.propertyValue) {
        field.Name = "propertyValue";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(PropertyValue);
        oprot.WriteFieldEnd();
      }
      if (__isset.confidence) {
        field.Name = "confidence";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Confidence);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("ProfilePropertyValue(");
    bool __first = true;
    if (ProfileId != null && __isset.profileId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ProfileId: ");
      __sb.Append(ProfileId);
    }
    if (PropertyName != null && __isset.propertyName) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("PropertyName: ");
      __sb.Append(PropertyName);
    }
    if (PropertyValue != null && __isset.propertyValue) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("PropertyValue: ");
      __sb.Append(PropertyValue);
    }
    if (__isset.confidence) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Confidence: ");
      __sb.Append(Confidence);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

