/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class PropertyHit : TBase
{
  private string _value;
  private string _label;
  private long _totalHitCount;

  public string Value
  {
    get
    {
      return _value;
    }
    set
    {
      __isset.@value = true;
      this._value = value;
    }
  }

  public string Label
  {
    get
    {
      return _label;
    }
    set
    {
      __isset.label = true;
      this._label = value;
    }
  }

  public long TotalHitCount
  {
    get
    {
      return _totalHitCount;
    }
    set
    {
      __isset.totalHitCount = true;
      this._totalHitCount = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool @value;
    public bool label;
    public bool totalHitCount;
  }

  public PropertyHit() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 11:
            if (field.Type == TType.String) {
              Value = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 21:
            if (field.Type == TType.String) {
              Label = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 31:
            if (field.Type == TType.I64) {
              TotalHitCount = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("PropertyHit");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Value != null && __isset.@value) {
        field.Name = "value";
        field.Type = TType.String;
        field.ID = 11;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Value);
        oprot.WriteFieldEnd();
      }
      if (Label != null && __isset.label) {
        field.Name = "label";
        field.Type = TType.String;
        field.ID = 21;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Label);
        oprot.WriteFieldEnd();
      }
      if (__isset.totalHitCount) {
        field.Name = "totalHitCount";
        field.Type = TType.I64;
        field.ID = 31;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(TotalHitCount);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("PropertyHit(");
    bool __first = true;
    if (Value != null && __isset.@value) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Value: ");
      __sb.Append(Value);
    }
    if (Label != null && __isset.label) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Label: ");
      __sb.Append(Label);
    }
    if (__isset.totalHitCount) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("TotalHitCount: ");
      __sb.Append(TotalHitCount);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

